name: "Pull Request Reviewer"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  add-reviewer:
    if: ${{ github.actor != 'modular-magician' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        # File .github/auto_assign.yml is used by this action
